typelevel/mouse

jvm/src/test/scala/com/github/benhutchison/mouse/StringJvmTests.scala, shared/src/main/scala/com/github/benhutchison/mouse/all.scala, shared/src/main/scala/com/github/benhutchison/mouse/package.scala, shared/src/main/scala/com/github/benhutchison/mouse/string.scala, shared/src/test/scala/com/github/benhutchison/mouse/BooleanSyntaxTest.scala, shared/src/test/scala/com/github/benhutchison/mouse/MouseSuite.scala, shared/src/test/scala/com/github/benhutchison/mouse/OptionSyntaxTest.scala, shared/src/test/scala/com/github/benhutchison/mouse/StringTests.scala
Adds primitive parsing for:
- `Byte`
- `Short`
- `Long`
- `Int`
- `Short`
- `Float`
- `Double`
- `Boolean`
Note the float parsing test is in the `jvm` tree because JavaScript does some weird things with floats.
This PR was originally against https://github.com/typelevel/cats/pull/876
=> Adds StringOps for parsing primitives.

shared/src/main/scala/mouse/boolean.scala, shared/src/test/scala/mouse/BooleanSyntaxTest.scala
Adds `fold` method to `BooleanOps`. Also changes (deprecated) `xor` to `either` in tests.
The syntax methods are marked as final and are reimplemented in terms of `fold`.
=> Boolean fold

build.sbt, shared/src/test/scala/mouse/AnySyntaxTest.scala
Fixed compiler warnings around:
1. Implicit conversions
2. Deprecations (adaptation of argument list by inserting ())
Enabled feature warnings by default.
=> Fix compiler warnings

README.md, build.sbt, shared/src/main/scala/mouse/all.scala, shared/src/main/scala/mouse/package.scala, shared/src/main/scala/mouse/try.scala, shared/src/test/scala/mouse/TrySyntaxTest.scala
Added the following try operations:
1. cata
2. either
Updated examples and used pattern matching to get around missing __fold__
method on scala.util.Try in Scala 2.10 and 2.11.
=> Add try operations

shared/src/main/scala/mouse/try.scala, shared/src/test/scala/mouse/TrySyntaxTest.scala
Renamed the **either** method on **TryOps** to **toEither** to match
the **toEither** method added to **scala.util.Try** in Scala 2.12.
The **TrySyntax** will add an implicit conversion on **scala.util.Try**
to add the **toEither** method for Scala 2.10 and 2.11 and will use the
default **toEither** method when on Scala 2.12.
=> Rename either to toEither on TryOps

shared/src/main/scala/mouse/boolean.scala, shared/src/main/scala/mouse/option.scala, shared/src/main/scala/mouse/string.scala, shared/src/main/scala/mouse/try.scala
This does `@inline` on most of the methods. While it can be argued that this is redundant due to JIT, here are some counter arguments
1. Making the JIT do less work is always preferable
2. May not always imply for other platforms (scala.js and scala-native)
3. JIT can sometimes fail if the methods aren't call enough times
The only downside is if the implementations of the `@inline` method changes, but this is highly unlikely in such a library (and it would be done in a new version of mouse anyways)
=> Inlining all of the things

shared/src/main/scala/mouse/any.scala, shared/src/main/scala/mouse/package.scala
This PR adds kestrel (<|) and unsafeTap to `any` syntax, which are intended to be removed from cats-collections (https://github.com/typelevel/cats-collections/issues/105). Also, now it is possible to import `mouse.any._`
=> Add kestrel & unsafeTap, introduce granular `any` syntax

build.sbt, project/build.properties, shared/src/main/scala/mouse/map.scala, shared/src/test/scala/mouse/MapSyntaxTest.scala
This PR adds three more convenience methods for `Map[A, B]` for updating single keys using a function, a semigroup or an effectful function (used `Option` in the tests, but works for any `Applicative`, most useful with monads like `cats.effect.IO`).
Also bumps Scala version to 2.12.8 and sbt to 1.2.7.
=> Extends MapOps

shared/src/main/scala/mouse/string.scala, shared/src/test/scala/mouse/StringSyntaxTests.scala
This PR adds `parseBigInt` and `parseBigDecimal` extension methods to `StringOps`. They work the same as the other functions to parse number values from strings.
=> Add parseBigInt and parseBigDecimal to String syntax

.travis.yml
It looks like Travis have removed their `oraclejdk8` JDK from the default distribution (see [this issue](https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038/9)). This is causing build failures ([example](https://travis-ci.org/typelevel/mouse/jobs/575150115)).
I've tried to fix this by using `openjdk8` instead of `oraclejdk8`. Manually specifying the distribution with `dist: trusty` may also work, but I don't see any reason to prefer the Oracle JDK to OpenJDK.
=> Use openjdk8 on Travis CI instead of oraclejdk8

shared/src/main/scala/mouse/boolean.scala, shared/src/test/scala/mouse/BooleanSyntaxTest.scala
This is useful for the common (for me at least) situation where based
on the value of a boolean you want to either run another effect or
just return a pure value.
Not at all attached to the name, in fact I think it's a bit confusing
because it's not clear that 'value' means something wrapped in an
Applicatve.
=> Add a valueOrPure method to boolean.

README.md, shared/src/main/scala/mouse/boolean.scala, shared/src/test/scala/mouse/BooleanSyntaxTest.scala
Just added a one-line helper function to BooleanOps that will apply a function to a value if the boolean is true and return the value unchanged if it's false. I feel I've needed this thing often enough that I'd like to have it in a library.
This pull request contains the obvious implementation: `def applyIf[A, B](a: A)(f: A => A): A = if (b) f(a) else a` . But it doesn't infer the type correctly for something like this:
```scala
def mutilate(x: CharSequence): CharSequence = x.subSequence(3, 5)
true.applyIf("foo")(mutilate)
```
Hence an implementation like this might be more desirable:
```scala
class ApplyIfPartiallyApplied[A](a: A) {
@inline def apply[B >: A](f: B => B): B = if (b) f(a) else a
}
@inline def applyIf[A](a:A) = new ApplyIfPartiallyApplied[A](a)
```
But otoh, the latter will …
=> add applyIf helper function to BooleanOps

shared/src/main/scala/mouse/string.scala, shared/src/test/scala/mouse/StringSyntaxTests.scala
(This PR has been moved from https://github.com/typelevel/cats/pull/3938)
Getting quick-and-dirty errors from string error messages is a pretty common use case. This PR is similar to `asLeft`/`asRight` and `some`/`none` but not widened for `Error`/`Exception` subtypes as they are not ADTs.
Instead of writing this:
```scala
val leftError = Left(new Error("error"))
val ioThrow = new Throwable("error").raiseError[IO, Unit]
```
this PR lets you do this:
```scala
val leftError = "error".asError.asLeft
val ioThrow = "error".asThrowable.raiseError[IO, Unit]
```
Saves you from writing the `new` keyword and parentheses.
=> add methods for creating generic errors from string

.github/workflows/ci.yml, build.sbt, shared/src/test/scala/mouse/StringSyntaxTests.scala
This fixes warnings about using parentheses for lambdas and also updates Scala 3 version to the latest.
=> Scala 3 cleanup

.scalafmt.conf
Within the current version of the `Scalafmt` dialect should be specified explicitly. Otherwise used deprecated default. And warning `Default dialect is deprecated; use explicit: [Scala211,scala212,Scala212Source3,scala213,Scala213Source3,Sbt0137,Sbt1,scala3]` is produced on every fmt command.
=> Specify dialect for `Scalafmt`

shared/src/main/scala-2.x/src/main/scala/mouse/tuple.scala, shared/src/test/scala-2.x/mouse/TupleSyntaxTest.scala
The notation of that operators is taken from Scala 3 `Tuple` methods:
`*:` — stands for `prepend` https://github.com/lampepfl/dotty/blob/master/library/src/scala/Tuple.scala#L32
`:*` — stands for `append` https://github.com/lampepfl/dotty/blob/master/library/src/scala/Tuple.scala#L26
It'll allow smooth migration on Scala 3 by simply deleting the `mouse.tuple._` import.
=> Add `append` and `prepend` operators to the tuple syntax

shared/src/main/scala/mouse/feither.scala, shared/src/main/scala/mouse/foption.scala, shared/src/test/scala/mouse/FEitherSyntaxTest.scala, shared/src/test/scala/mouse/FOptionSyntaxTest.scala
Adding some extension methods that I often wish I had. It really boils down to code cleanliness preferences.
I just wanted to get some feedback on whether others feel like these conversions belong here, or if they're fundamentally anathema/broken in some non-obvious way.
If others are amenable then I will write some tests and correct the formatting
=> Convenience functions for lifting to OptionT & EitherT

shared/src/main/scala/mouse/anyf.scala, shared/src/main/scala/mouse/foption.scala, shared/src/test/scala/mouse/AnyFSyntaxTest.scala, shared/src/test/scala/mouse/FOptionSyntaxTest.scala
Added convenient methods that enable us to write:
```scala
fa.liftEitherT[E] // EitherT[F, E, A]
fa.liftOptionT // OptionT[F, A]
foptiona.liftEitherT("none") // EitherT[F, String, A]
```
Consequence of https://github.com/typelevel/cats/issues/4068
=> Enhanced syntax for creation EitherT/OptionT

shared/src/main/scala/mouse/any.scala, shared/src/main/scala/mouse/feither.scala, shared/src/main/scala/mouse/foption.scala, shared/src/test/scala/mouse/AnySyntaxTest.scala, shared/src/test/scala/mouse/FEitherSyntaxTest.scala, shared/src/test/scala/mouse/FOptionSyntaxTest.scala
This adds `asLeftF`, `asRightF`, `noneF`, `someF` methods to `AnySyntax`, `FEitherSyntax` and `FOptionSyntax`.
Those methods are utterly useful in daily programming. They're replacing such constructs as:
```scala
none[Int].pure[F] // noneF
42.some.pure[F] // 42.someF
"foo".asLeft[Int].pure[F] // "foo".asLeftF
```
=> Add `asLeftF`, `asRightF`, `noneF`, `someF` methods

README.md
1.0 version was released about 1 year ago. We should thin the readme for better readability, I suggest.
=> Thin `README`

js/src/main/scala/mouse/package.scala, jvm/src/main/scala-2/src/main/scala/mouse/package.scala, jvm/src/main/scala-3/src/main/scala/mouse/package.scala, shared/src/main/scala-2/src/main/scala/mouse/all.scala, shared/src/main/scala-3/src/main/scala/mouse/all.scala, shared/src/main/scala/mouse/fboolean.scala, shared/src/test/scala/mouse/FBooleanSyntaxTests.scala
Migrated from **cats**: https://github.com/typelevel/cats/pull/4114
IMHO these three operations are useful and relatively common enough that is good to have them, especially the `andM` & `orM` since they preserve the short-circuit behavior from traditional boolean operations.
Let me know what you all think and if the test / scaladoc are good.
=> Add F[Boolean] syntax

.github/workflows/ci.yml, build.sbt
That's previous behavior, so I think we should go with it right now.
=> Publish releases for tags only

build.sbt, js/src/main/scala/mouse/package.scala, jvm/src/main/scala-2/src/main/scala/mouse/package.scala, jvm/src/main/scala-3/src/main/scala/mouse/package.scala, project/Boilerplate.scala, project/GenFTupleNSyntax.scala, shared/src/main/scala-2/src/main/scala/mouse/all.scala, shared/src/main/scala-3/src/main/scala/mouse/all.scala, shared/src/main/scala/mouse/ftuple.scala, shared/src/test/scala/mouse/FTupleNSyntaxSuite.scala
This migrated from https://github.com/typelevel/cats/pull/4125.
There is no syntax for Tuple2 because of `cats.syntax.FunctorTuple2Ops`.
At this point, `cats.syntax` is a kinda monolith that probably wouldn't be changed/extended in foreseeable future. So, Mouse to the rescue :)
=> Add `F[TupleN]` syntax

shared/src/main/scala/mouse/boolean.scala, shared/src/test/scala/mouse/BooleanSyntaxTest.scala
These additional extensions aligns the boolean to validated methods with similar methods in Cats, which usually provide all three options.
=> Add validated and validatedNec to boolean

shared/src/main/scala/mouse/feither.scala, shared/src/main/scala/mouse/foption.scala, shared/src/test/scala/mouse/FEitherSyntaxTest.scala, shared/src/test/scala/mouse/FOptionSyntaxTest.scala
Hi, dealing with nested effects is always complex and sometimes verbose, I found helpful these two methods in my codebase and I'd like to propose them here.
`getOrRaiseF`  and `getOrRaiseMsgF` given `F[G[A]]` where `F` is a `MonadError` and `G` a foldable like `Option` and `Either` we can either get the nested value or raise an error in `F` if the value is missing ( since either is right biased).
Example
```scala
val fga: Try[Option[Int]] = Success(None)
val result: Try[Int] = fga.getOrRaiseMsgF("BOOM!")// = Failure(RuntimeException("BOOM!")
```
What do you think? (There are alternatives already in place? )
=> Add getOrRaiseF

build.sbt
Importing `mouse` in IntelliJ ( I didn't try with other IDEs) the project name is `root` since there isn't any name specified to the main root SBT project. 
This is annoying when you want to open the project and, searching for `mouse` you get no results
=> Add project name to sbt root project.

shared/src/main/scala/mouse/feither.scala, shared/src/test/scala/mouse/FEitherSyntaxTest.scala
Hi! First of all, thanks for this great library.
I use IO[Either[A, B]] heavily and I found these functions quite useful. I think they fit nice since `EitherT` has similar functions. What do you think?
=> Add bimapIn, swapIn and mergeIn to FEitherSyntax

shared/src/main/scala/mouse/feither.scala, shared/src/main/scala/mouse/foption.scala, shared/src/test/scala/mouse/FEitherSyntaxTest.scala, shared/src/test/scala/mouse/FOptionSyntaxTest.scala
This pull request adds `toRightIn` to `FOptionOps` and `toOptionIn` to `FEitherOps`, as discussed in #338. I can also add `toLeftInF` and `toRightInF` (as suggested by @satorg) in a separate PR, if you find these two methods helpful as well.
=> Add `toRightIn` and `toOptionIn`

shared/src/main/scala/mouse/foption.scala, shared/src/test/scala/mouse/FOptionSyntaxTest.scala
This pull request adds `toLeftInF` and `toRightInF` to `FOptionOps`, as proposed by @satorg in #338. It also adds missing `toLeftIn` method, for symmetry
=> Add `toLeftInF` and `toRightInF`

shared/src/main/scala/mouse/option.scala, shared/src/test/scala/mouse/OptionSyntaxTest.scala
Since support for scala 2.11 has been dropped and the next scala versions has correct return type, we can deprecate this methods and remove in the future
=> Deprecate `left` and `right` methods on Option

.github/workflows/ci.yml, build.sbt
As time has shown, @armanbilge was right about snapshot publishing. It's better to have it enabled.
=> Enable snapshots publishing from the 'main' branch

.github/workflows/ci.yml, build.sbt
Here I suggest launching the `series/2.x` branch to unlock the development (possibly non-binary compatible) of a new major series. Site publishing is still should proceed with the `main` branch, but snapshot publishing should work to enable early bird access.
=> Launch `series/2.x` branch

shared/src/main/scala/mouse/feither.scala, shared/src/test/scala/mouse/FEitherSyntaxTest.scala
I think this might be a nice replacement for
```scala
_.leftMapIn[WiderType](identity)
```
=> introduce leftWidenIn for F[Either[L, R]]

shared/src/main/scala/mouse/feither.scala, shared/src/test/scala/mouse/FEitherSyntaxTest.scala
This is a counterpart method for already added [`leftWidenIn`](https://github.com/typelevel/mouse/pull/375).
=> Add `widenIn` to `FEither` syntax

DEV.md, docs/contributing-guide.md
This adds a new section in the contributing guide which emphasises several `mouse` branches that are under active development.
=> Update the contributing guide

js/src/main/scala-2/mouse/package.scala, js/src/main/scala-3/mouse/package.scala, jvm/src/main/scala-2/src/main/scala/mouse/package.scala, jvm/src/main/scala-3/src/main/scala/mouse/package.scala, native/src/main/scala-2/mouse/mouse.scala, native/src/main/scala-3/mouse/package.scala, shared/src/main/scala-2/src/main/scala/mouse/all.scala, shared/src/main/scala-3/src/main/scala/mouse/all.scala, shared/src/test/scala/mouse/AnySyntaxTest.scala
Motivation: [inheritance for package objects was deprecated](https://github.com/scala/scala-dev/issues/441) some time ago. Also, this is not a binary-compatible change, so we can't fix that for the `1.x` series.
=> Reorganise `mouse` package object

shared/src/main/scala/mouse/feither.scala, shared/src/main/scala/mouse/foption.scala, shared/src/test/scala/mouse/FEitherSyntaxTest.scala, shared/src/test/scala/mouse/FOptionSyntaxTest.scala
Hi guys! This PR adds some useful methods based on `mapIn` and `leftMapIn`.
**F[Option[A]]**
- `asIn` -> map `F[Option[A]]`  to `F[Option[B]]` ignoring the `A` value.
- `voidIn` -> drain `F[Option[A]]`  to `F[Option[Unit]]` ignoring the `A` value.
**F[Either[L, R]]**
- `asIn` -> map `F[Either[L, R]]`  to `F[Either[L, B]]` ignoring the `R` value.
- `voidIn` -> drain `F[Either[L, R]]`  to `F[Either[L, Unit]]` ignoring the `R` value.
- `leftAsIn`  -> map `F[Either[L, R]]`  to `F[Either[B, R]]` ignoring the `L` value.
- `leftVoidIn` -> drain `F[Either[L, R]]`  to `F[Either[Unit, R]]` ignoring the `L` value.
What do you think ?
=> Add asIn, voidIn, leftAsIn, leftVoidIn into foption and feither.

shared/src/main/scala/mouse/anyf.scala, shared/src/test/scala/mouse/AnyFSyntaxTest.scala
Hi guys! This PR adds some methods to map an `F[A]` into `F[Either[L, A]]`, `F[Either[A, R]]` or `F[Option[A]]`.
Example
```scala
val fa: IO[Int] = IO.pure(1)
val faRight: IO[Either[String, Int]] = fa.asRightIn[String]
val faLeft: IO[Either[Int, String]] = fa.asLeftIn[String]
val faOption: IO[Option[Int]] = fa.asSomeIn
```
And for the naming, here a recap
```scala
val a: Int = 1 
val fa: IO[Int] = IO.pure(a)
val right: Either[String, Int] = a.asRight[String]
val faRightFromA: IO[Either[String, Int]] = a.asRightF[IO, String]
val faRightFromFA: IO[Either[String, Int]] = fa.mapAsRight[String]
```
What do you think ? Is there already something in place that I didn't found ? If not, do you think the name is coherent ?
=> Add asRightIn, asLeftIn and asSomeIn for anyF

shared/src/main/scala/mouse/feither.scala, shared/src/main/scala/mouse/foption.scala, shared/src/test/scala/mouse/FEitherSyntaxTest.scala, shared/src/test/scala/mouse/FOptionSyntaxTest.scala
These are counterpart methods to newly shipped `Functor#mapOrKeep` and `Monad#flatMapOrKeep` methods in Cats. From my tastes, `mapOrKeepIn` might be highly useful while `flatMapOrKeepIn` is not as much as the former. But I still decided to add it too and have complete conformity with Cats.
=> Add `mapOrKeepIn` / `flatMapOrKeepIn` to `F[Option[A]]` and `F[Either[A,B]]` syntaxes

shared/src/main/scala/mouse/feither.scala, shared/src/test/scala/mouse/FEitherSyntaxTest.scala
It's a companion PR to https://github.com/typelevel/cats/pull/4638
=> Add `leftMapOrKeepIn` / `leftFlatMapOrKeepIn` to `F[Either[A,B]]` syntax
