typelevel/mouse

- jvm/src/test/scala/com/github/benhutchison/mouse/StringJvmTests.scala
- shared/src/main/scala/com/github/benhutchison/mouse/all.scala
- shared/src/main/scala/com/github/benhutchison/mouse/package.scala
- shared/src/main/scala/com/github/benhutchison/mouse/string.scala
- shared/src/test/scala/com/github/benhutchison/mouse/BooleanSyntaxTest.scala
- shared/src/test/scala/com/github/benhutchison/mouse/MouseSuite.scala
- shared/src/test/scala/com/github/benhutchison/mouse/OptionSyntaxTest.scala
- shared/src/test/scala/com/github/benhutchison/mouse/StringSyntaxTests.scala
- shared/src/test/scala/com/github/benhutchison/mouse/StringTests.scala
Adds functions that return `Validated` to complement `Xor` and `Option`.
> Parse validated

- shared/src/main/scala/mouse/all.scala
- shared/src/main/scala/mouse/any.scala
- shared/src/main/scala/mouse/package.scala
- shared/src/test/scala/mouse/AnySyntaxTest.scala
Resolves https://github.com/benhutchison/mouse/issues/13
First time Typelevel contributor, let me know if any smells.
Adds AnySyntax with |> and ignore
Adds really simple tests for |> and ignore
> Thrush and ignore syntax

- README.md
Add README update for #17. Unfortunately I didn't notice this omission
until today 😞  .
> Update README to reflect either method rename

- build.sbt
This updates to cats 1.0.0-MF … easy peasy. 
Many downstream cats libs are publishing milestones depending on 1.0.0-MF so we will all be ready when the final release happens. It would be great to see one from mouse!
> cats-1.0.0-MF

- .travis.yml
- README.md
- build.sbt
- project/build.properties
- version.sbt
https://github.com/typelevel/general/issues/84
> Migration to typelevel organisation

- shared/src/main/scala/mouse/boolean.scala
- shared/src/test/scala/mouse/BooleanSyntaxTest.scala
Adds operators `valueOrZero`, `zeroOrValue`, `??`, `!?`
Let me know what you think.
> Add Boolean Monoid Operators Syntax

- build.sbt
- shared/src/main/scala/mouse/any.scala
- shared/src/main/scala/mouse/double.scala
- shared/src/main/scala/mouse/option.scala
- shared/src/main/scala/mouse/package.scala
- shared/src/main/scala/mouse/try.scala
Mostly just formatting changes for consistency.
Also bumped cats version and removed an unused import from build.sbt.
> Minor clean up, document `ignore`.

- shared/src/main/scala/mouse/any.scala
- shared/src/main/scala/mouse/boolean.scala
- shared/src/main/scala/mouse/double.scala
- shared/src/main/scala/mouse/int.scala
- shared/src/main/scala/mouse/long.scala
- shared/src/main/scala/mouse/option.scala
- shared/src/main/scala/mouse/string.scala
- shared/src/main/scala/mouse/try.scala
> Remove `final` from methods in final classes.

- .travis.yml
- build.sbt
- project/plugins.sbt
(I'm not sure whether it's acceptable in this repo to depend on a Cats milestone)
> support Scala 2.13.0-RC1 (drop M5)

- README.md
-  Add missing prompt
- Remove duplicate line
> Fix details on example REPL session

- .travis.yml
- build.sbt
- project/plugins.sbt
- shared/src/test/scala/mouse/MouseSuite.scala
It's necessarily to update scalatest as well as it's not published for scalajs 1.x
> Update dependencies and Scala 2.12

- jvm/src/main/scala/mouse/stringJvm.scala
- jvm/src/test/scala/mouse/StringJvmTests.scala
Adds support for parsing `java.util.UUID` from strings on JVM.
> Add support for parsing UUID for JVM

- build.sbt
- jvm/src/test/scala/mouse/StringJvmTests.scala
- shared/src/test/scala/mouse/AnyFSyntaxTest.scala
- shared/src/test/scala/mouse/AnySyntaxTest.scala
- shared/src/test/scala/mouse/BooleanSyntaxTest.scala
- shared/src/test/scala/mouse/DoubleSyntaxTest.scala
- shared/src/test/scala/mouse/IntSyntaxTest.scala
- shared/src/test/scala/mouse/LongSyntaxTest.scala
- shared/src/test/scala/mouse/MapSyntaxTest.scala
- shared/src/test/scala/mouse/MouseSuite.scala
- shared/src/test/scala/mouse/OptionSyntaxTest.scala
- shared/src/test/scala/mouse/PartialFunctionLiftTest.scala
- shared/src/test/scala/mouse/StringSyntaxTests.scala
- shared/src/test/scala/mouse/TrySyntaxTest.scala
This PR aims to unify the test framework in `cats`-based projects in `typelevel` org.
> Use MUnit in tests

- build.sbt
> Bump the previous Mouse version in the `build.sbt`

- shared/src/main/scala/mouse/boolean.scala
> Add type annotation to the `BooleanOps.valueOrPure`

- docs/index.md
Also, it would be good to add a link to the site in the repo settings (in the repository details).
> Add link to the site in the readme

- .github/workflows/ci.yml
- build.sbt
Seems you are checking it twice 😉
> Remove redundant fmt check

- build.sbt
- js/src/main/scala-3/mouse/TupleSyntax.scala
Not sure why this was missing! 😁
> Publish for Scala 3 + JS

- .github/workflows/ci.yml
- build.sbt
Follow-up from https://github.com/typelevel/sbt-typelevel/issues/430.
> Use `tlCrossRootProject`

- DEV.md
- docs/contributing-guide.md
> Tweak the contributing guide one more time

- build.sbt
A small follow-up to https://github.com/typelevel/mouse/pull/489.
> Refactor settings related to sbt-header in build.sbt
